name = "shrill_emerald_marsupial-4206"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "shrill_emerald_marsupial-4206_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "shrill_emerald_marsupial-4206.wasm"
command = "npm run build:release"
